title: Chris Wang
# Comment out url when working locally to resolve base urls correctly
url: https://itskkk.github.io
baseurl: /KangW0916.github.io

# Default social-share preview image. Lives in /images/.
og_image: header-avatar.jpg

# Owner/author information
owner:
  name: Chris Wang
  avatar: header-avatar.jpg
  email: itsk0916@gmail.com
  github: itskkk
  scholar: "https://scholar.google.com/citations?user=dDul1N4AAAAJ&hl=zh-CN"

# Links to include in top navigation
links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai
future: true
highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
